FROM jboss/base-jdk:8

ENV DEBIAN_FRONTEND noninteractive

# Set the WILDFLY_VERSION env variable
ENV WILDFLY_VERSION 18.0.1.Final
ENV WILDFLY_SHA1 ef0372589a0f08c36b15360fe7291721a7e3f7d9
ENV JBOSS_HOME /opt/jboss/wildfly

USER root
RUN groupmod -g 2000 jboss && usermod -u 2000 jboss

RUN cd $HOME \
    && curl -O https://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz \
    && sha1sum wildfly-$WILDFLY_VERSION.tar.gz | grep $WILDFLY_SHA1 \
    && tar xf wildfly-$WILDFLY_VERSION.tar.gz \
    && mv $HOME/wildfly-$WILDFLY_VERSION $JBOSS_HOME \
    && rm wildfly-$WILDFLY_VERSION.tar.gz \
    && chown -R jboss:0 ${JBOSS_HOME} \
    && chmod -R g+rw ${JBOSS_HOME}

#COPY instance.conf /opt/jboss/instance.conf
#COPY run-standalone.sh /opt/jboss/run-standalone.sh
#RUN chown jboss:jboss -R /opt/jboss && chmod a+x /opt/jboss/run-standalone.sh
RUN chown jboss:jboss -Rf /opt/jboss

# RUN mkdir -p /opt/jboss/wildfly/standalone/log && \
#      ln -sf /dev/null /opt/jboss/wildfly/standalone/log/server.log
# RUN mkdir -p /opt/jboss/wildfly/standalone/log && chown -R jboss.jboss /opt/jboss/wildfly/standalone/log
# VOLUME /opt/jboss/wildfly/standalone/log

# Expose the ports we're interested in
EXPOSE 8080

# Ensure signals are forwarded to the JVM process correctly for graceful shutdown
ENV LAUNCH_JBOSS_IN_BACKGROUND true

USER jboss

# Set the default command to run on boot
# This will boot WildFly in the standalone mode and bind to all interface
#CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]
CMD ["/opt/jboss/wildfly/bin/standalone.sh"]